### ISSUE TITLE
Trouble with templates, very inconsistent in my experience. 

### ISSUE THREAD

**Issue by vide0hanz** [deviantfero/wpgtk-templates#15]
Hey again, is there some sort of dependency required to get the templates feature working correctly? I have not had consistent luck in getting them working. 

Here's what I've tried:

I create a test file and import it into wpgtk templates. I go to edit the .base file and fill with keywords {color1} {color2} {color3}... etc, save the changes, set the colors and.... nothing. They do not update. 

Oddly enough, this feature was working before I did a clean install on my most recent system.

**Comment by deviantfero** [comment]
open this issue on `wpgtk` repository, but it could have something to do with how you install wpgtk, it should be installed system-wide, or at least I haven't actually tested with a --user flag on the pip package.
