### ISSUE TITLE
FlatColor Theme not working

### ISSUE THREAD

**Issue by MuhammedTaha02** [deviantfero/wpgtk-templates#19]
Hello, I using Swaywm on Gentoo Linux. But gtk2 theme not correctly working. The theme looks like this in lxappearance.

![image](https://user-images.githubusercontent.com/62564400/110896693-298f4200-830d-11eb-98ae-0494abb4dcda.png)

How can i fix this problem? Thanks.

**Comment by deviantfero** [comment]
I  think you need gtk-engine-murrine in your system, try installing that and let me know if it worked for you

**Comment by MuhammedTaha02** [comment]
I had set up that program. But it didn't work. I fixed the solution by downgrading the lxappearance version on gentoo. Thank you for your attention :)
