### ISSUE TITLE
Invisible checkboxes in xfce4-power-manager.

### ISSUE THREAD

**Issue by b1scu1t** [deviantfero/wpgtk-templates#4]
Hi, I have encountered a visual error with the FlatColor theme.

There's a pop-up menu that appears when I right-click the xfce4-power-manager system-tray icon. Normally it would show a checkbox to toggle 'presentation mode' the menu, but its missing when I use the FlatColor theme.

**_Below is a screenshot using the Adwaita-dark theme._**
![crop_screenshot_2019-01-14_01-12-11](https://user-images.githubusercontent.com/41207956/51098839-68fc8b00-17a3-11e9-998b-63aa2d01c378.png)

**_Below is a screenshot using the FlatColor theme (Base 16 Dark). (Missing checkbox)_** 
![crop_screenshot_2019-01-14_01-07-04](https://user-images.githubusercontent.com/41207956/51098970-29826e80-17a4-11e9-8010-b57e4bb5ea2e.png)

This is the JSON color scheme I use (Base 16 Default Dark).
I can't upload .json files, so I changed the extension to .txt.
[default.dark.txt](https://github.com/deviantfero/wpgtk-templates/files/2754189/default.dark.txt)

I have not edited the GTK 2.0,3.0 or 3.20 base configuration files for FlatColor; the whole theme is a verbatim copy from this repository.

Thanks for all your help.

**Comment by deviantfero** [comment]
Thanks for bringing this to my attention, I'll see what I can do, I was planning on a small update soon anyway

**Comment by deviantfero** [comment]
hi there, this has been fixed, along with other things in the theme, you can re-install using `wpg-install.sh` ;) please let me know if it's fixed for you.

**Comment by b1scu1t** [comment]
Sorry for the long wait.
I ran these commands:
```
wpg-install.sh -g
wpg -s ether_3_piece-suites.jpg
```
The check-boxes are still invisible on xfce4-power-manager's right click menu.
However, they are visible on Xfce4-settings-manager (though, the sliders may be difficult to see).
![screenshot_2019-01-15_13-00-49](https://user-images.githubusercontent.com/41207956/51196526-ac4f1a80-18c5-11e9-903d-3f8f52a3c204.png)

I've also manually removed `~/.config/wpg` and `~/.themes` directories, before re-running the aforementioned commands above.

**Comment by deviantfero** [comment]
pushed to the wrong repo @b1scu1t, lol dumb me, please try again

**Comment by b1scu1t** [comment]
It works!

**This is presentation mode toggled 'on'**
![crop_screenshot_2019-01-15_15-04-13](https://user-images.githubusercontent.com/41207956/51203363-3e135380-18d7-11e9-90a7-5ad922de34cc.png)

**This is presentation mode toggled 'off'**
![crop_screenshot_2019-01-15_15-16-56](https://user-images.githubusercontent.com/41207956/51203999-f1c91300-18d8-11e9-8fbb-5f0fe30a039c.png)

Thanks a lot!

Your response time was pretty darn quick.
Keep up the good work!
