### ISSUE TITLE
flattrcolor icon theme is missing some application categories.

### ISSUE THREAD

**Issue by b1scu1t** [deviantfero/wpgtk-templates#5]
Hello, I encountered an error with the flattrcolor theme, where most application categories are missing in the applications menu.

However, the icons appear while using the default Adwaita or Gnome icon themes.

I'm using the default 'Applications Menu' plugin for xfce4-panel.

**Here's a screenshot using the Adwaita theme.**
![image](https://user-images.githubusercontent.com/41207956/51225247-0e3c6e00-1920-11e9-8ac1-54e0013de50d.png)

**Here's a screenshot using the flattrcolor theme.**
![image](https://user-images.githubusercontent.com/41207956/51225190-c61d4b80-191f-11e9-8903-59e4053c4b93.png)

Oddly enough, the xfce4-whisker-plugin (alternative menu) seems to fallback on Gnome icons for the missing categories.
![image](https://user-images.githubusercontent.com/41207956/51225319-73905f00-1920-11e9-914e-9528d6347d2b.png)

Again, thanks for your help.

**Comment by deviantfero** [comment]
yep. this one can be tougher for me, I'll also see what I can do, but I don't promise to be as fast ;)

**Comment by b1scu1t** [comment]
Would you like to re-base the icons template to [Luv](https://github.com/Nitrux/luv-icon-theme)?

I see that Luv is a spiritual successor to 'Flattr' by the same Nitrux team, but redoing the icons template may be tedious. 

I would also like to help your project, how can I assist?

**Comment by deviantfero** [comment]
I actually think it would be easier to add the missing icons to the icon set, most of these could be fixed by creating the appropriate symbolic links, I could use a way to preview all icons that a system may use, so I can see which are missing, do you know of something like that?

**Comment by b1scu1t** [comment]
Sorry, I don't know any software like that.
I think the our best bet is using is following the [specification].(https://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html)

I'm particularly looking at the 'Standard category icons' section.

**Comment by b1scu1t** [comment]
I don't think any new icons need to be 'imported' per se.

Reading from `~/.icons/flattrcolor/categories` , it looks like the  icons exist in the 'scalable' sub-directory, but not in the '48' and '64' directories.

Maybe, the scalable icons aren't referenced in `~/.icons/flattrcolor/index.theme` ?

P.S Sorry about responding so late.

**Comment by deviantfero** [comment]
don't worry about it, I don't actually have much time to do this, but it is something I want to take care about, I'm aware that most icons do exist, but links and icon names change through time, so most of the work is actually symlinking existing icons to the appropiate directories and name.
